  jwt:
    private:
      key: classpath:app.key
    public:
      key: classpath:app.pub

server:
  servlet:
    context-path: /accounts

spring:
  application:
    name: contas
  datasource:
    url: jdbc:postgresql://localhost:5432/contas
    username: user
    password: user@123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:localhost/migration
    baseline-on-migrate: true
  jpa:
    open-in-view: false